In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('C:/Users/migue/OneDrive/Documentos/MachineLearning_Basis/classification_data.csv')

In [3]:
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-100,2000,15,12,...,0,1,0,0.0,0.0,0.8,0.8,19,40,22
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-174,2000,25,10,...,0,3,1,1.7,1.7,1.2,2.9,26,31,56
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,20-231,2003,7,1,...,0,0,0,0.1,0.1,0.1,0.2,2,5,7
3,4,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,36-198,1987,25,25,...,0,4,0,2.4,2.4,0.3,2.7,33,117,7
4,5,Salis Abdul Samed,gh GHA,MF,Lens,fr Ligue 1,24-018,2000,25,17,...,0,2,0,0.8,0.8,0.5,1.3,8,77,20

In [6]:
df['Pos'] = df['Pos'].apply(lambda x: x.split(',')[0])

In [9]:
df['Pos'].unique()

array(['DF', 'MF', 'FW', 'GK'], dtype=object)

In [8]:
df = df[df['Pos'] != 'Pos']

In [10]:
df.isnull().sum()

Rk           0
Player       0
Nation       3
Pos          0
Squad        0
Comp         0
Age          3
Born         3
MP           0
Starts       0
Min          0
90s          0
Gls          0
Ast          0
G+A          0
G-PK         0
PK           0
PKatt        0
CrdY         0
CrdR         0
xG          14
npxG        14
xAG         14
npxG+xAG    14
PrgC        14
PrgP        14
PrgR        14
dtype: int64

In [12]:
df = df.dropna()

print(df.shape)

(2737, 27)

In [13]:
df['Pos'].value_counts()

Pos
DF    977
MF    870
FW    711
GK    179
Name: count, dtype: int64

In [14]:
df['Pos'].value_counts().max() / df['Pos'].value_counts().sum()

np.float64(0.35696017537449765)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

df['Pos'] = le.fit_transform(df['Pos'])

print(df['Pos'].unique())

[0 3 1 2]

In [17]:
print(le.inverse_transform(df['Pos'].unique()))

['DF' 'MF' 'FW' 'GK']

In [18]:
df[df['Pos'] == 2]

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR
31,31,Julen Agirrezabala,es ESP,2,Athletic Club,es La Liga,23-109,2000,1,1,...,0,0,0,0.0,0.0,0.0,0.0,0,0,0
76,75,Alisson,br BRA,2,Liverpool,eng Premier League,31-194,1992,21,21,...,0,1,0,0.0,0.0,0.0,0.0,0,2,0
130,126,Alphonse Areola,fr FRA,2,West Ham,eng Premier League,31-046,1993,27,27,...,0,1,0,0.0,0.0,0.0,0.0,0,1,0
142,138,Kepa Arrizabalaga,es ESP,2,Real Madrid,es La Liga,29-193,1994,12,12,...,0,1,0,0.0,0.0,0.0,0.0,0,0,0
154,150,Noah Atubolu,de GER,2,Freiburg,de Bundesliga,21-324,2002,28,28,...,0,0,0,0.0,0.0,0.0,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2707,2604,Guglielmo Vicario,it ITA,2,Tottenham,eng Premier League,27-189,1996,31,31,...,0,2,0,0.0,0.0,0.0,0.0,0,1,0
2719,2616,Iván Villar,es ESP,2,Celta Vigo,es La Liga,26-279,1997,10,10,...,0,0,2,0.0,0.0,0.1,0.1,0,0,0
2734,2630,Odisseas Vlachodimos,gr GRE,2,Nott'ham Forest,eng Premier League,29-353,1994,5,5,...,0,0,0,0.0,0.0,0.0,0.0,0,1,0
2839,2731,Robin Zentner,de GER,2,Mainz 05,de Bundesliga,29-168,1994,24,24,...,0,3,0,0.0,0.0,0.0,0.0,0,1,0
2844,2736,Michael Zetterer,de GER,2,Werder Bremen,de Bundesliga,28-276,1995,21,21,...,0,1,0,0.1,0.1,0.2,0.3,0,3,0

In [19]:
df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP',
       'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt',
       'CrdY', 'CrdR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP',
       'PrgR'],
      dtype='object')

In [23]:
X = df[['Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt',
       'CrdY', 'CrdR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP',
       'PrgR']]

y = df['Pos']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2, random_state=42)

In [25]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [26]:
from sklearn.metrics import accuracy_score

y_pred = clf.predict(X_test)

accuracy_score(y_test, y_pred)

0.614963503649635

In [27]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[121,  11,  11,  58],
       [ 13,  90,   5,  26],
       [  0,   0,  29,   2],
       [ 45,  31,   9,  97]])

In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.60      0.64       201
           1       0.68      0.67      0.68       134
           2       0.54      0.94      0.68        31
           3       0.53      0.53      0.53       182

    accuracy                           0.61       548
   macro avg       0.61      0.69      0.63       548
weighted avg       0.62      0.61      0.61       548